class Container_Base;

class PlateCarrierPouches: Container_Base {};
class PlateCarrierPouches_IntenZ: PlateCarrierPouches
{
	hiddenSelections[]=
	{
		"camoGround",
		"camoMale",
		"camoFemale"
	};
	hiddenSelectionsTextures[]=
	{
		"Intenz_Images\Textures\PlateCarrier\IntenZ_co.paa",
		"Intenz_Images\Textures\PlateCarrier\IntenZ_co.paa",
		"Intenz_Images\Textures\PlateCarrier\IntenZ_co.paa"
	};
};
class PlateCarrierPouches_White: PlateCarrierPouches
{
	hiddenSelections[]=
	{
		"camoGround",
		"camoMale",
		"camoFemale"
	};
	hiddenSelectionsTextures[]=
	{
		"Intenz_Images\Textures\PlateCarrier\White_co.paa",
		"Intenz_Images\Textures\PlateCarrier\White_co.paa",
		"Intenz_Images\Textures\PlateCarrier\White_co.paa"
	};
};
class PlateCarrierPouches_Black: PlateCarrierPouches
{
	hiddenSelections[]=
	{
		"camoGround",
		"camoMale",
		"camoFemale"
	};
	hiddenSelectionsTextures[]=
	{
		"Intenz_Images\Textures\PlateCarrier\Black_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Black_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Black_co.paa"
	};
};
class PlateCarrierPouches_Grey: PlateCarrierPouches
{
	hiddenSelections[]=
	{
		"camoGround",
		"camoMale",
		"camoFemale"
	};
	hiddenSelectionsTextures[]=
	{
		"Intenz_Images\Textures\PlateCarrier\Grey_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Grey_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Grey_co.paa"
	};
};
class PlateCarrierPouches_Blue: PlateCarrierPouches
{
	hiddenSelections[]=
	{
		"camoGround",
		"camoMale",
		"camoFemale"
	};
	hiddenSelectionsTextures[]=
	{
		"Intenz_Images\Textures\PlateCarrier\Blue_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Blue_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Blue_co.paa"
	};
};
class PlateCarrierPouches_LightGreen: PlateCarrierPouches
{
	hiddenSelections[]=
	{
		"camoGround",
		"camoMale",
		"camoFemale"
	};
	hiddenSelectionsTextures[]=
	{
		"Intenz_Images\Textures\PlateCarrier\Light_Green_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Light_Green_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Light_Green_co.paa"
	};
};
class PlateCarrierPouches_Green: PlateCarrierPouches
{
	hiddenSelections[]=
	{
		"camoGround",
		"camoMale",
		"camoFemale"
	};
	hiddenSelectionsTextures[]=
	{
		"Intenz_Images\Textures\PlateCarrier\Green_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Green_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Green_co.paa"
	};
};
class PlateCarrierPouches_Dark_Green: PlateCarrierPouches
{
	hiddenSelections[]=
	{
		"camoGround",
		"camoMale",
		"camoFemale"
	};
	hiddenSelectionsTextures[]=
	{
		"Intenz_Images\Textures\PlateCarrier\Dark_Green_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Dark_Green_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Dark_Green_co.paa"
	};
};
class PlateCarrierPouches_Brown: PlateCarrierPouches
{
	hiddenSelections[]=
	{
		"camoGround",
		"camoMale",
		"camoFemale"
	};
	hiddenSelectionsTextures[]=
	{		
		"Intenz_Images\Textures\PlateCarrier\Brown_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Brown_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Brown_co.paa"
	};
};
