class Container_Base;
class PlateCarrierPouches: Container_Base {};

class PlateCarrierPouches_IntenZ: PlateCarrierPouches
{
	hiddenSelections[]=
	{
		"camoGround",
		"camoMale",
		"camoFemale"
	};
	hiddenSelectionsTextures[]=
	{
		"Intenz_Images\Textures\PlateCarrier\Vest\IntenZ_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Vest\IntenZ_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Vest\IntenZ_co.paa"
	};
};
class PlateCarrierPouches_White: PlateCarrierPouches
{
	hiddenSelections[]=
	{
		"camoGround",
		"camoMale",
		"camoFemale"
	};
	hiddenSelectionsTextures[]=
	{
		"Intenz_Images\Textures\PlateCarrier\Vest\White_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Vest\White_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Vest\White_co.paa"
	};
};
class PlateCarrierPouches_Black: PlateCarrierPouches
{
	hiddenSelections[]=
	{
		"camoGround",
		"camoMale",
		"camoFemale"
	};	
	hiddenSelectionsTextures[]=
	{
		"Intenz_Images\Textures\PlateCarrier\Vest\Black_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Vest\Black_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Vest\Black_co.paa"
	};
};
class PlateCarrierPouches_Grey: PlateCarrierPouches
{
	hiddenSelections[]=
	{
		"camoGround",
		"camoMale",
		"camoFemale"
	};	
	hiddenSelectionsTextures[]=
	{
		"Intenz_Images\Textures\PlateCarrier\Vest\Grey_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Vest\Grey_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Vest\Grey_co.paa"
	};
};
class PlateCarrierPouches_Blue: PlateCarrierPouches
{
	hiddenSelections[]=
	{
		"camoGround",
		"camoMale",
		"camoFemale"
	};	
	hiddenSelectionsTextures[]=
	{
		"Intenz_Images\Textures\PlateCarrier\Vest\Blue_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Vest\Blue_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Vest\Blue_co.paa"
	};
};
class PlateCarrierPouches_LightGreen: PlateCarrierPouches
{
	hiddenSelections[]=
	{
		"camoGround",
		"camoMale",
		"camoFemale"
	};
	hiddenSelectionsTextures[]=
	{
		"Intenz_Images\Textures\PlateCarrier\Vest\Light_Green_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Vest\Light_Green_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Vest\Light_Green_co.paa"
	};
};
class PlateCarrierPouches_Green: PlateCarrierPouches
{
	hiddenSelections[]=
	{
		"camoGround",
		"camoMale",
		"camoFemale"
	};
	hiddenSelectionsTextures[]=
	{
		"Intenz_Images\Textures\PlateCarrier\Vest\Green_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Vest\Green_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Vest\Green_co.paa"
	};
};
class PlateCarrierPouches_Dark_Green: PlateCarrierPouches
{
	hiddenSelections[]=
	{
		"camoGround",
		"camoMale",
		"camoFemale"
	};	
	hiddenSelectionsTextures[]=
	{
		"Intenz_Images\Textures\PlateCarrier\Vest\Dark_Green_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Vest\Dark_Green_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Vest\Dark_Green_co.paa"
	};
};
class PlateCarrierPouches_Brown: PlateCarrierPouches
{
	hiddenSelections[]=
	{
		"camoGround",
		"camoMale",
		"camoFemale"
	};	
	hiddenSelectionsTextures[]=
	{
		"Intenz_Images\Textures\PlateCarrier\Vest\Brown_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Vest\Brown_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Vest\Brown_co.paa"
	};
};
