class PlateCarrierVest: Clothing {};
class PlateCarrier_ColorBase{};

class PlateCarrierVest_IntenZ: PlateCarrierVest
{
	hiddenSelections[]=
	{
		"camoGround",
		"camoMale",
		"camoFemale"
	};
	hiddenSelectionsTextures[]=
	{
		"Intenz_Images\Textures\PlateCarrier\IntenZ_co.paa",
		"Intenz_Images\Textures\PlateCarrier\IntenZ_co.paa",
		"Intenz_Images\Textures\PlateCarrier\IntenZ_co.paa"
	};
};
class PlateCarrierVest_White: PlateCarrierVest
{
	hiddenSelections[]=
	{
		"camoGround",
		"camoMale",
		"camoFemale"
	};
	hiddenSelectionsTextures[]=
	{
		"Intenz_Images\Textures\PlateCarrier\White_co.paa",
		"Intenz_Images\Textures\PlateCarrier\White_co.paa",
		"Intenz_Images\Textures\PlateCarrier\White_co.paa"
	};
};
class PlateCarrierVest_Black: PlateCarrierVest
{
	hiddenSelections[]=
	{
		"camoGround",
		"camoMale",
		"camoFemale"
	};
	hiddenSelectionsTextures[]=
	{
		"Intenz_Images\Textures\PlateCarrier\Black_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Black_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Black_co.paa"
	};
};
class PlateCarrierVest_Grey: PlateCarrierVest
{
	hiddenSelections[]=
	{
		"camoGround",
		"camoMale",
		"camoFemale"
	};
	hiddenSelectionsTextures[]=
	{
		"Intenz_Images\Textures\PlateCarrier\Grey_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Grey_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Grey_co.paa"
	};
};
class PlateCarrierVest_Blue: PlateCarrierVest
{
	hiddenSelections[]=
	{
		"camoGround",
		"camoMale",
		"camoFemale"
	};
	hiddenSelectionsTextures[]=
	{
		"Intenz_Images\Textures\PlateCarrier\Blue_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Blue_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Blue_co.paa"
	};
};
class PlateCarrierVest_LightGreen: PlateCarrierVest
{
	hiddenSelections[]=
	{
		"camoGround",
		"camoMale",
		"camoFemale"
	};
	hiddenSelectionsTextures[]=
	{
		"Intenz_Images\Textures\PlateCarrier\Light_Green_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Light_Green_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Light_Green_co.paa"
	};
};
class PlateCarrierVest_Green: PlateCarrierVest
{
	hiddenSelections[]=
	{
		"camoGround",
		"camoMale",
		"camoFemale"
	};
	hiddenSelectionsTextures[]=
	{
		"Intenz_Images\Textures\PlateCarrier\Green_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Green_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Green_co.paa"
	};
};
class PlateCarrierVest_Dark_Green: PlateCarrierVest
{
	hiddenSelections[]=
	{
		"camoGround",
		"camoMale",
		"camoFemale"
	};
	hiddenSelectionsTextures[]=
	{
		"Intenz_Images\Textures\PlateCarrier\Dark_Green_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Dark_Green_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Dark_Green_co.paa"
	};
};
class PlateCarrierVest_Brown: PlateCarrierVest
{
	hiddenSelections[]=
	{
		"camoGround",
		"camoMale",
		"camoFemale"
	};
	hiddenSelectionsTextures[]=
	{
		"Intenz_Images\Textures\PlateCarrier\Brown_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Brown_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Brown_co.paa"
	};
};
