class PlateCarrierVest: Clothing {};
class PlateCarrier_ColorBase{};

class PlateCarrierVest_IntenZ: PlateCarrierVest
{
	hiddenSelections[]=
	{
		"camoGround",
		"camoMale",
		"camoFemale"
	};
	hiddenSelectionsTextures[]=
	{
		"Intenz_Images\Textures\PlateCarrier\Vest\IntenZ_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Vest\IntenZ_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Vest\IntenZ_co.paa"
	};
};
class PlateCarrierVest_White: PlateCarrierVest
{
	hiddenSelections[]=
	{
		"camoGround",
		"camoMale",
		"camoFemale"
	};
	hiddenSelectionsTextures[]=
	{
		"Intenz_Images\Textures\PlateCarrier\Vest\White_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Vest\White_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Vest\White_co.paa"
	};
};
class PlateCarrierVest_Black: PlateCarrierVest
{
	hiddenSelections[]=
	{
		"camoGround",
		"camoMale",
		"camoFemale"
	};
	hiddenSelectionsTextures[]=
	{
		"Intenz_Images\Textures\PlateCarrier\Vest\Black_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Vest\Black_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Vest\Black_co.paa"
	};
};
class PlateCarrierVest_Grey: PlateCarrierVest
{
	hiddenSelections[]=
	{
		"camoGround",
		"camoMale",
		"camoFemale"
	};
	hiddenSelectionsTextures[]=
	{
		"Intenz_Images\Textures\PlateCarrier\Vest\Grey_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Vest\Grey_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Vest\Grey_co.paa"
	};
};
class PlateCarrierVest_Blue: PlateCarrierVest
{
	hiddenSelections[]=
	{
		"camoGround",
		"camoMale",
		"camoFemale"
	};
	hiddenSelectionsTextures[]=
	{
		"Intenz_Images\Textures\PlateCarrier\Vest\Blue_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Vest\Blue_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Vest\Blue_co.paa"
	};
};
class PlateCarrierVest_LightGreen: PlateCarrierVest
{
	hiddenSelections[]=
	{
		"camoGround",
		"camoMale",
		"camoFemale"
	};
	hiddenSelectionsTextures[]=
	{
		"Intenz_Images\Textures\PlateCarrier\Vest\Light_Green_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Vest\Light_Green_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Vest\Light_Green_co.paa"
	};
};
class PlateCarrierVest_Green: PlateCarrierVest
{
	hiddenSelections[]=
	{
		"camoGround",
		"camoMale",
		"camoFemale"
	};
	hiddenSelectionsTextures[]=
	{
		"Intenz_Images\Textures\PlateCarrier\Vest\Green_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Vest\Green_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Vest\Green_co.paa"
	};
};
class PlateCarrierVest_Dark_Green: PlateCarrierVest
{
	hiddenSelections[]=
	{
		"camoGround",
		"camoMale",
		"camoFemale"
	};
	hiddenSelectionsTextures[]=
	{
		"Intenz_Images\Textures\PlateCarrier\Vest\Dark_Green_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Vest\Dark_Green_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Vest\Dark_Green_co.paa"
	};
};
class PlateCarrierVest_Brown: PlateCarrierVest
{
	hiddenSelections[]=
	{
		"camoGround",
		"camoMale",
		"camoFemale"
	};
	hiddenSelectionsTextures[]=
	{
		"Intenz_Images\Textures\PlateCarrier\Vest\Brown_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Vest\Brown_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Vest\Brown_co.paa"
	};
};
