class PlateCarrierHolster: Clothing {};

class PlateCarrierHolster_IntenZ: PlateCarrierHolster
{
	hiddenSelections[]=
	{
		"camoGround",
		"camoMale",
		"camoFemale"
	};
	hiddenSelectionsTextures[]=
	{
		"Intenz_Images\Textures\PlateCarrier\IntenZ_co.paa",
		"Intenz_Images\Textures\PlateCarrier\IntenZ_co.paa",
		"Intenz_Images\Textures\PlateCarrier\IntenZ_co.paa"
	};
};
class PlateCarrierHolster_White: PlateCarrierHolster
{
	hiddenSelections[]=
	{
		"camoGround",
		"camoMale",
		"camoFemale"
	};
	hiddenSelectionsTextures[]=
	{
		"Intenz_Images\Textures\PlateCarrier\White_co.paa",
		"Intenz_Images\Textures\PlateCarrier\White_co.paa",
		"Intenz_Images\Textures\PlateCarrier\White_co.paa"
	};
};
class PlateCarrierHolster_Black: PlateCarrierHolster
{
	hiddenSelections[]=
	{
		"camoGround",
		"camoMale",
		"camoFemale"
	};
	hiddenSelectionsTextures[]=
	{
		"Intenz_Images\Textures\PlateCarrier\Black_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Black_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Black_co.paa"
	};
};
class PlateCarrierHolster_Grey: PlateCarrierHolster
{
	hiddenSelections[]=
	{
		"camoGround",
		"camoMale",
		"camoFemale"
	};
	hiddenSelectionsTextures[]=
	{
		"Intenz_Images\Textures\PlateCarrier\Grey_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Grey_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Grey_co.paa"
	};
};
class PlateCarrierHolster_Blue: PlateCarrierHolster
{
	hiddenSelections[]=
	{
		"camoGround",
		"camoMale",
		"camoFemale"
	};
	hiddenSelectionsTextures[]=
	{
		"Intenz_Images\Textures\PlateCarrier\Blue_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Blue_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Blue_co.paa"
	};
};
class PlateCarrierHolster_LightGreen: PlateCarrierHolster
{
	hiddenSelections[]=
	{
		"camoGround",
		"camoMale",
		"camoFemale"
	};
	hiddenSelectionsTextures[]=
	{
		"Intenz_Images\Textures\PlateCarrier\Light_Green_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Light_Green_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Light_Green_co.paa"
	};
};
class PlateCarrierHolster_Green: PlateCarrierHolster
{
	hiddenSelections[]=
	{
		"camoGround",
		"camoMale",
		"camoFemale"
	};
	hiddenSelectionsTextures[]=
	{
		"Intenz_Images\Textures\PlateCarrier\Green_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Green_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Green_co.paa"
	};
};
class PlateCarrierHolster_Dark_Green: PlateCarrierHolster
{
	hiddenSelections[]=
	{
		"camoGround",
		"camoMale",
		"camoFemale"
	};
	hiddenSelectionsTextures[]=
	{
		"Intenz_Images\Textures\PlateCarrier\Dark_Green_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Dark_Green_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Dark_Green_co.paa"
	};
};
class PlateCarrierHolster_Brown: PlateCarrierHolster
{
	hiddenSelections[]=
	{
		"camoGround",
		"camoMale",
		"camoFemale"
	};
	hiddenSelectionsTextures[]=
	{		
		"Intenz_Images\Textures\PlateCarrier\Brown_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Brown_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Brown_co.paa"
	};
};
