class PlateCarrierHolster: Clothing {};

class PlateCarrierHolster_IntenZ: PlateCarrierHolster
{
	hiddenSelections[]=
	{
		"camoGround",
		"camoMale",
		"camoFemale"
	};
	hiddenSelectionsTextures[]=
	{
		"Intenz_Images\Textures\PlateCarrier\Vest\IntenZ_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Vest\IntenZ_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Vest\IntenZ_co.paa"
	};
};
class PlateCarrierHolster_White: PlateCarrierHolster
{
	hiddenSelections[]=
	{
		"camoGround",
		"camoMale",
		"camoFemale"
	};
	hiddenSelectionsTextures[]=
	{
		"Intenz_Images\Textures\PlateCarrier\Vest\White_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Vest\White_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Vest\White_co.paa"
	};
};
class PlateCarrierHolster_Black: PlateCarrierHolster
{
	hiddenSelections[]=
	{
		"camoGround",
		"camoMale",
		"camoFemale"
	};
	hiddenSelectionsTextures[]=
	{
		"Intenz_Images\Textures\PlateCarrier\Vest\Black_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Vest\Black_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Vest\Black_co.paa"
	};
};
class PlateCarrierHolster_Grey: PlateCarrierHolster
{
	hiddenSelections[]=
	{
		"camoGround",
		"camoMale",
		"camoFemale"
	};
	hiddenSelectionsTextures[]=
	{
		"Intenz_Images\Textures\PlateCarrier\Vest\Grey_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Vest\Grey_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Vest\Grey_co.paa"
	};
};
class PlateCarrierHolster_Blue: PlateCarrierHolster
{
	hiddenSelections[]=
	{
		"camoGround",
		"camoMale",
		"camoFemale"
	};
	hiddenSelectionsTextures[]=
	{
		"Intenz_Images\Textures\PlateCarrier\Vest\Blue_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Vest\Blue_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Vest\Blue_co.paa"
	};
};
class PlateCarrierHolster_LightGreen: PlateCarrierHolster
{
	hiddenSelections[]=
	{
		"camoGround",
		"camoMale",
		"camoFemale"
	};
	hiddenSelectionsTextures[]=
	{
		"Intenz_Images\Textures\PlateCarrier\Vest\Light_Green_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Vest\Light_Green_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Vest\Light_Green_co.paa"
	};
};
class PlateCarrierHolster_Green: PlateCarrierHolster
{
	hiddenSelections[]=
	{
		"camoGround",
		"camoMale",
		"camoFemale"
	};
	hiddenSelectionsTextures[]=
	{
		"Intenz_Images\Textures\PlateCarrier\Vest\Green_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Vest\Green_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Vest\Green_co.paa"
	};
};
class PlateCarrierHolster_Dark_Green: PlateCarrierHolster
{
	hiddenSelections[]=
	{
		"camoGround",
		"camoMale",
		"camoFemale"
	};
	hiddenSelectionsTextures[]=
	{
		"Intenz_Images\Textures\PlateCarrier\Vest\Dark_Green_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Vest\Dark_Green_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Vest\Dark_Green_co.paa"
	};
};
class PlateCarrierHolster_Brown: PlateCarrierHolster
{
	hiddenSelections[]=
	{
		"camoGround",
		"camoMale",
		"camoFemale"
	};
	hiddenSelectionsTextures[]=
	{		
		"Intenz_Images\Textures\PlateCarrier\Vest\Brown_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Vest\Brown_co.paa",
		"Intenz_Images\Textures\PlateCarrier\Vest\Brown_co.paa"
	};
};
