class Container_Base;

class PlateCarrierPouches: Container_Base {};
class PlateCarrierPouches_IntenZ: PlateCarrierPouches
{
	hiddenSelections[]=
	{
		"camoGround",
		"camoMale",
		"camoFemale"
	};
	hiddenSelectionsTextures[]=
	{
		"IntenZ\Assets\textures\platecarrier\intenz_co.paa",
		"IntenZ\Assets\textures\platecarrier\intenz_co.paa",
		"IntenZ\Assets\textures\platecarrier\intenz_co.paa"
	};
};
class PlateCarrierPouches_White: PlateCarrierPouches
{
	hiddenSelections[]=
	{
		"camoGround",
		"camoMale",
		"camoFemale"
	};
	hiddenSelectionsTextures[]=
	{
		"IntenZ\Assets\textures\platecarrier\white_co.paa",
		"IntenZ\Assets\textures\platecarrier\white_co.paa",
		"IntenZ\Assets\textures\platecarrier\white_co.paa"
	};
};
class PlateCarrierPouches_Black: PlateCarrierPouches
{
	hiddenSelections[]=
	{
		"camoGround",
		"camoMale",
		"camoFemale"
	};
	hiddenSelectionsTextures[]=
	{
		"IntenZ\Assets\textures\platecarrier\black_co.paa",
		"IntenZ\Assets\textures\platecarrier\black_co.paa",
		"IntenZ\Assets\textures\platecarrier\black_co.paa"
	};
};
class PlateCarrierPouches_Grey: PlateCarrierPouches
{
	hiddenSelections[]=
	{
		"camoGround",
		"camoMale",
		"camoFemale"
	};
	hiddenSelectionsTextures[]=
	{
		"IntenZ\Assets\textures\platecarrier\grey_co.paa",
		"IntenZ\Assets\textures\platecarrier\grey_co.paa",
		"IntenZ\Assets\textures\platecarrier\grey_co.paa"
	};
};
class PlateCarrierPouches_Blue: PlateCarrierPouches
{
	hiddenSelections[]=
	{
		"camoGround",
		"camoMale",
		"camoFemale"
	};
	hiddenSelectionsTextures[]=
	{
		"IntenZ\Assets\textures\platecarrier\blue_co.paa",
		"IntenZ\Assets\textures\platecarrier\blue_co.paa",
		"IntenZ\Assets\textures\platecarrier\blue_co.paa"
	};
};
class PlateCarrierPouches_LightGreen: PlateCarrierPouches
{
	hiddenSelections[]=
	{
		"camoGround",
		"camoMale",
		"camoFemale"
	};
	hiddenSelectionsTextures[]=
	{
		"IntenZ\Assets\textures\platecarrier\light_green_co.paa",
		"IntenZ\Assets\textures\platecarrier\light_green_co.paa",
		"IntenZ\Assets\textures\platecarrier\light_green_co.paa"
	};
};
class PlateCarrierPouches_Green: PlateCarrierPouches
{
	hiddenSelections[]=
	{
		"camoGround",
		"camoMale",
		"camoFemale"
	};
	hiddenSelectionsTextures[]=
	{
		"IntenZ\Assets\textures\platecarrier\green_co.paa",
		"IntenZ\Assets\textures\platecarrier\green_co.paa",
		"IntenZ\Assets\textures\platecarrier\green_co.paa"
	};
};
class PlateCarrierPouches_Dark_Green: PlateCarrierPouches
{
	hiddenSelections[]=
	{
		"camoGround",
		"camoMale",
		"camoFemale"
	};
	hiddenSelectionsTextures[]=
	{
		"IntenZ\Assets\textures\platecarrier\dark_green_co.paa",
		"IntenZ\Assets\textures\platecarrier\dark_green_co.paa",
		"IntenZ\Assets\textures\platecarrier\dark_green_co.paa"
	};
};
class PlateCarrierPouches_Brown: PlateCarrierPouches
{
	hiddenSelections[]=
	{
		"camoGround",
		"camoMale",
		"camoFemale"
	};
	hiddenSelectionsTextures[]=
	{		
		"IntenZ\Assets\textures\platecarrier\brown_co.paa",
		"IntenZ\Assets\textures\platecarrier\brown_co.paa",
		"IntenZ\Assets\textures\platecarrier\brown_co.paa"
	};
};
